// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZCMUWWmlX7fRaIiMradpzzoRB6xpNeMI',
    appId: '1:700494509769:web:6ea64dc1fba552b8f97f18',
    messagingSenderId: '700494509769',
    projectId: 'my-test-app-e35b3',
    authDomain: 'my-test-app-e35b3.firebaseapp.com',
    storageBucket: 'my-test-app-e35b3.firebasestorage.app',
    measurementId: 'G-4HQ20XF2EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkKaez9dA_UXlpazNg9xlh1PeBvV727Xg',
    appId: '1:700494509769:android:b579f716a5f88725f97f18',
    messagingSenderId: '700494509769',
    projectId: 'my-test-app-e35b3',
    storageBucket: 'my-test-app-e35b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADYhh2j2vrtmywWcneITbxGLPhUtoxN-8',
    appId: '1:700494509769:ios:afc6febc736dbae6f97f18',
    messagingSenderId: '700494509769',
    projectId: 'my-test-app-e35b3',
    storageBucket: 'my-test-app-e35b3.firebasestorage.app',
    iosBundleId: 'com.example.webTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADYhh2j2vrtmywWcneITbxGLPhUtoxN-8',
    appId: '1:700494509769:ios:afc6febc736dbae6f97f18',
    messagingSenderId: '700494509769',
    projectId: 'my-test-app-e35b3',
    storageBucket: 'my-test-app-e35b3.firebasestorage.app',
    iosBundleId: 'com.example.webTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZCMUWWmlX7fRaIiMradpzzoRB6xpNeMI',
    appId: '1:700494509769:web:13bc0be309bf444ff97f18',
    messagingSenderId: '700494509769',
    projectId: 'my-test-app-e35b3',
    authDomain: 'my-test-app-e35b3.firebaseapp.com',
    storageBucket: 'my-test-app-e35b3.firebasestorage.app',
    measurementId: 'G-ZCNHDWLJLT',
  );
}
