@startuml
'https://plantuml.com/state-diagram

scale 350 width
hide empty description
[*] --> Home
Home --> Mark : Push mark button
Home --> Share : Push Share button
Home --> Check : Push Check button

state Mark{
[*] --> SelectSheet
SelectSheet --> input : Select Free Mode
SelectSheet --> CreateNewSheet : Push + button
CreateNewSheet -> input

SelectSheet --> Continue : Push from history
Continue -l> input
Continue -d>  getItm
getItm -u> Continue

input --> finish
finish --> Check.SelectAnswerFIle : Select Auto Score
finish --> Check.SelfInput : Select Manual Score
finish --> SaveMark : Select Save Mark
SaveMark --> finish : Finish Save Mark
}

state Share{
[*] --> ShareHome
ShareHome --> Share.import
ShareHome --> Share.export
}

state Check{
[*] --> CheckHome
CheckHome --> SelectAnswerFIle
CheckHome --> SelfInput

SelfInput--> ShowScore
SelectAnswerFIle --> ShowScore
SelectAnswerFIle --> import
}


@enduml