@startuml
'https://plantuml.com/state-diagram

scale 350 width
hide empty description
[*] --> Home
Home --> Mark : Push mark button
Home --> Share : Push Share button
Home --> Check : Push Check button

state Mark{
[*] --> SelectSheet
SelectSheet -d--> input : Select Sheet on view
SelectSheet --> CreateNewSheet : Push + button
CreateNewSheet -> input



input --> finish : push "complete button"
finish --> Check.SelectAnswerFIle : Select Auto Score
finish --> Check.SelfInput : Select Manual Score
}

state Share{
[*] --> ShareHome
ShareHome --> Share.import
ShareHome --> Share.export
}

state Check{
SheetList:保存済みシートが並んでおり、それぞれAutoとSelfのボタンがある。
[*] --> SheetList
SheetList --> SelectAnswerFIle
SheetList --> SelfInput

SelfInput--> ShowScore
SelectAnswerFIle --> ShowScore
SelectAnswerFIle --> import
}

@enduml